# in bash load packages
module load python/3.10.x-anaconda 

# activate the conda env. 
conda activate ISS 

cd /project/pathology/SiZhang_lab/shared/Active_Projects/UTSW24_CC_PAIR_perturb/01.RawData/PAIR

[s208205@Nucleus005 mRNA]$ cat *.txt
808f13e9666f440ceda09e224362bf0e  mRNA-SI_TT_A7_22TFMKLT3_S3_L008_R1_001.fastq.gz
fa4d925083b2890d875cf1f10ab1120e  mRNA-SI_TT_A7_22TFMKLT3_S3_L008_R2_001.fastq.gz
d58ff4efbbef0e2327752644bb3f9360  mRNA-SI_TT_A7_22TFMKLT3_S3_L008_I1_001.fastq.gz
8a3c37ef9647a31e2803f048a6fb9f20  mRNA-SI_TT_A7_22TFMKLT3_S3_L008_I2_001.fastq.gz
8801ceef6d625518df7e7d1e609bac90  MD5.txt
d58ff4efbbef0e2327752644bb3f9360  mRNA-SI_TT_A7_22TFMKLT3_S3_L008_I1_001.fastq.gz
8a3c37ef9647a31e2803f048a6fb9f20  mRNA-SI_TT_A7_22TFMKLT3_S3_L008_I2_001.fastq.gz
808f13e9666f440ceda09e224362bf0e  mRNA-SI_TT_A7_22TFMKLT3_S3_L008_R1_001.fastq.gz
fa4d925083b2890d875cf1f10ab1120e  mRNA-SI_TT_A7_22TFMKLT3_S3_L008_R2_001.fastq.gz

[s208205@Nucleus005 PAIR]$ cat *.txt
56bef73fdef209fc6994e9235cb98ea1  PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R1_001.fastq.gz
5a7f137b2602e489038dab7c4af03630  PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R2_001.fastq.gz
dd33c8d388399557ec24aac49794c3f5  PAIR-SI_TT_A6_22TFMKLT3_S2_L008_I1_001.fastq.gz
4fd0052b461507ea6ecb5944512b4236  PAIR-SI_TT_A6_22TFMKLT3_S2_L008_I2_001.fastq.gz
ea08351e20210c64c4a85a2c16b93e6a  MD5.txt
dd33c8d388399557ec24aac49794c3f5  PAIR-SI_TT_A6_22TFMKLT3_S2_L008_I1_001.fastq.gz
4fd0052b461507ea6ecb5944512b4236  PAIR-SI_TT_A6_22TFMKLT3_S2_L008_I2_001.fastq.gz
56bef73fdef209fc6994e9235cb98ea1  PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R1_001.fastq.gz
5a7f137b2602e489038dab7c4af03630  PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R2_001.fastq.gz

[s208205@Nucleus005 HTO]$ cat *.txt
cba5bb423aad7d8c1f3a86b26bd3db70  HTO-SI_TN_A1_22TFMKLT3_S1_L008_R1_001.fastq.gz
f8187c208fe0e4630e2170b588ed7bb8  HTO-SI_TN_A1_22TFMKLT3_S1_L008_R2_001.fastq.gz
9ececbfb24bd1b74f324b2f40a547d23  HTO-SI_TN_A1_22TFMKLT3_S1_L008_I1_001.fastq.gz
a58ee2ac9a1c39d75931fe8b58f50625  HTO-SI_TN_A1_22TFMKLT3_S1_L008_I2_001.fastq.gz
9ececbfb24bd1b74f324b2f40a547d23  HTO-SI_TN_A1_22TFMKLT3_S1_L008_I1_001.fastq.gz
a58ee2ac9a1c39d75931fe8b58f50625  HTO-SI_TN_A1_22TFMKLT3_S1_L008_I2_001.fastq.gz
cba5bb423aad7d8c1f3a86b26bd3db70  HTO-SI_TN_A1_22TFMKLT3_S1_L008_R1_001.fastq.gz
f8187c208fe0e4630e2170b588ed7bb8  HTO-SI_TN_A1_22TFMKLT3_S1_L008_R2_001.fastq.gz
ad770c0d180943a8c352f3fa5840d325  MD5.txt
[s208205@Nucleus005 HTO]$ cat  MD5.txt
cba5bb423aad7d8c1f3a86b26bd3db70  HTO-SI_TN_A1_22TFMKLT3_S1_L008_R1_001.fastq.gz
f8187c208fe0e4630e2170b588ed7bb8  HTO-SI_TN_A1_22TFMKLT3_S1_L008_R2_001.fastq.gz
9ececbfb24bd1b74f324b2f40a547d23  HTO-SI_TN_A1_22TFMKLT3_S1_L008_I1_001.fastq.gz
a58ee2ac9a1c39d75931fe8b58f50625  HTO-SI_TN_A1_22TFMKLT3_S1_L008_I2_001.fastq.gz

# grep target handle sequences. TSO + POLD3 used as handle 
cd /project/pathology/SiZhang_lab/shared/Active_Projects/UTSW24_CC_PAIR_perturb/01.RawData/PAIR

# PAIR_perturb_whitelist_withID.csv
# ID	            CRISPRa	                CRISPRa_name	CasRx	                CasRx_name
# PAIR_Perturb_21	CTCAGCCAGTTGGCCTGCCA	NT_CRISPRa	    GATGTCATGCGTACGGGATAATC	NT_CasRx
# PAIR_Perturb_22	GTAGAAAACACCGAAGTGCG	POLD3_CRISPRa	CACATACACAAATGTGTGCACGT	PKcs-1_CasRx
# PAIR_Perturb_23	GTAGAAAACACCGAAGTGCG	POLD3_CRISPRa	GATGTCATGCGTACGGGATAATC	NT_CasRx
# PAIR_Perturb_24	GTCAGCCAGTTGGCCTGCCA	NT_CRISPRa	    CACATACACAAATGTGTGCACGT	PKcs-1_CasRx

# grep R1 using 5' of CRISPa gRNA as handle
[s208205@Nucleus005 PAIR]$ zcat PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R1_001.fastq.gz | awk '(NR%4==2) && /TTTCTTATATGGGG/' | head
ANTATAGCAGTCTGCACCGGTAAGGCGTTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCAAACATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
ANCGGCCTCCTCTGCAGTGTAGCTCGCGTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCAACCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
ANAACCTCAGGACCGACAGCCCGGGGGTTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCAACCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
GNAGATTTCCCCTTAGTGTCGCGACGGGTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCAACCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
GNATCCGAGATTACCGGTTAGGTCAGTCTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCAACCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
ANCATAACAAATCTCACCTCACAGGGATTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCAACCATGTCTGCAGGGCCTAGCAAGTTAAAATATAAGGCTAGTCCGTTATCAACTTGGCC
ANCGCAGGTGGCATATTAGGCGAGGTGGTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
GNATAGTGTGTGCGGTCCCGGTTTGGAGTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCAAACATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
GNCACTCCAAGTCGCCTTCGACCTGGGTTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCAACCATGTCTGCAGGGCCTAGCAAGCTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
ANAACCTCAGGACCGATGACACACCGGCTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCAACCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA

# grep target handle sequences. CRISPRa NT used as handle 
(ISS) [s208205@Nucleus005 PAIR]$ zcat PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R1_001.fastq.gz | awk '(NR%4==2) && /TTTCTTATATGGGGCTCAGCCAGTTGGCCTGCCA/' | head
AGGCTCGTCCTATACCCGCCTGCGTTAGTTTCTTATATGGGGCTCAGCCAGTTGGCCTGCCAGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
TCTTGTGTCGGTTAATGTCCAGCTCCCCCTGTATTATATGGGGGACTGGCACTTTCTTATATGGGGCTCAGCCAGTTGGCCTGCCAGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGG
ACTCAGGGTGCGAGAGCGAACGGTGGTGTTTCTTATATGGGGCTCAGCCAGTTGGCCTGCCAGTTTTAGAGCTAGGCCAACATGAGGATCAAACAGGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
GCCACTTGTATGATGCCGGTCAAATGGCTTTCTTATATGGGGCTCAGCCAGTTGGCCTGCCAGTTTTAGAGCTAGGCCAACATGAGGATCAAACATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
GCCACTTGTATGATGCCGGTCAAATGGCTTTCTTATATGGGGCTCAGCCAGTTGGCCTGCCAGTTTTAGAGCTAGGCCAACATGAGGATCAACCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
TTTCTCACACATAACCTTCTAGTACCTTTTTCTTATATGGGGCTCAGCCAGTTGGCCTGCCAGTTTTAGAGCTAGGCCAACATGAGGATCAAACATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
GTGCATGGTGGGAGCACACGCGAGACCATTTCTTATATGGGGCTCAGCCAGTTGGCCTGCCAGTTTTAGAGCTAGGCCAACATGAGGATCAACCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
ACCCACACAGTGAGCGGTACGTCCGACGTTTCTTATATGGGGCTCAGCCAGTTGGCCTGCCAGTTTTAGAGCTAGGCCAACATGAGGATCAACCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
AGTTAGTTCCCGAATACGCGCATTCCATTTTCTTATATGGGGCTCAGCCAGTTGGCCTGCCAGTTTTAGAGCTAGGCCAACATGAGGATCAAACATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
ATAACTATCAAATGTCACCTGAATGGGATTTCTTATATGGGGCTCAGCCAGTTGGCCTGCCAGTTTTAGAGCTAGGCCAACATGAGGATCAACCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA

# grep target shorter lead at 5' of CasRx crRNA , the next 23 bases are CasRx crRNA RC GATTATCCCGTACGCATGACATC
(ISS) [s208205@Nucleus005 PAIR]$ zcat PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R2_001.fastq.gz | awk '(NR%4==2) && /TTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTG/' | head
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGGATTATCCCGTACGCATGACATCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGGATTATCCCGTACGCATGACATCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTACCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGGATTATCCCGTACGCATGACATCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAGGCACCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGACGTGCACACATTTGTGTATGTGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAG
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGGATTATCCCGTACGCATGACATCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTATTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGGATTATCCCGTACGCATGACATCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTATTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGGATTATCCCGTACGCATGACATCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCATCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGGATTATCCCGTACGCATGACATCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTATTTGACGCACCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGGATTATCCCGTACGCATGACATCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGGATTATCCCGTACGCATGACATCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTATTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGA

# grep target handle sequences. NT_CasRx RC GATTATCCCGTACGCATGACATC as handle 
(ISS) [s208205@Nucleus005 PAIR]$ zcat PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R2_001.fastq.gz | awk '(NR%4==2) && /GATTATCCCGTACGCATGACATC/' | head
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGGATTATCCCGTACGCATGACATCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGGATTATCCCGTACGCATGACATCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTACCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAACCCCCGACCAGTTGGTAGGGGTTTACTTGGATTATCCCGTACGCATGACATCGTTTCAAACCCCGACCAGTTAGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGGATTATCCCGTACGCATGACATCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAGGCACCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGGATTATCCCGTACGCATGACATCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTATTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGGATTATCCCGTACGCATGACATCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTATTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGGATTATCCCGTACGCATGACATCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCATCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGGATTATCCCGTACGCATGACATCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTATTTGACGCACCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGGATTATCCCGTACGCATGACATCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGGATTATCCCGTACGCATGACATCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTATTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGA

# grep target PKcs-1 RC region
(ISS) [s208205@Nucleus004 PAIR]$ zcat PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R2_001.fastq.gz | awk '(NR%4==2) && /ACGTGCACACATTTGTGTATGT/' | head
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGACGTGCACACATTTGTGTATGTGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAG
GGGGTGGGGGGGGGAGGAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGACGTGCACACATTTGTGTATGTGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTATTTGAAGCACCGCCTCGGTGCCACTTGGCACTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGACGTGCACACATTTGTGTATGTGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTATTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGACGTGCACACATTTGTGTATGTGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTATTTGACGCACCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGACGTGCACACATTTGTGTATGTGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGACGTGCACACATTTGTGTATGTGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAACCCCCGACCAGTTGGTAGGGGTTTACTTGACGTGCACACATTTGTGTATGTGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTAGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGACGTGCACACATTTGTGTATGTGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGACGTGCACACATTTGTGTATGTGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGA
TTGCTAGGACCGGCCTTAAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGACGTGCACACATTTGTGTATGTGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGA



# grep target handle sequences for mRNA library. 
[s208205@Nucleus004 01.RawData]$ zcat mRNA-SI_TT_A7_22TFMKLT3_S3_L008_R1_001.fastq.gz | head -n 12
@LH00328:476:22TFMKLT3:8:1101:41438:1032 1:N:0:TNCCAAGGGT+AAAGGTAGTA
ANCCCGTTCAATGTACCCACCCTCACCGTTTATTATATGGGATTTTCGTCTTAGCCACGCAGAAGTCGCGTGTCTAGGTGAGTCGCGGTGGGTCCTCGCTTGCAGTTCAGCGACCACGTTTGTTTCGACGCCGGACCGCGTAAGAGACGA
+
I#IIIIIIIIIIIIIIIIIIIIIIIIIIII9--I--IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IIIIIIIII-I9IIIII-I-IIIIIIII9III9IIIIIII9III-9I
@LH00328:476:22TFMKLT3:8:1101:42214:1032 1:N:0:TNCCAAGGGT+AAAGGTAGTA
CNGCAACAGAAACTAGCAGACGAGGGGGTTTCTTATATGGGGCTTCTCGCCTAACGCTGCCAACATGGTGTTCAGGCGCTTCGTGGAGGTTGGCCGGGTGGCCTATGTCTCCTTTGGATCTCATGCCGGAAAATTGGTCGCGATTGTAGA
+
I#IIIIIIIIIIIIIIIIIIIIIIIIIIII9IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IIIIIII9IIIIIIIIIIIIIIII9I9II-I-IIIIIIIIIIIIIIIIIIIIIIIIIIIII9I
@LH00328:476:22TFMKLT3:8:1101:43435:1032 1:N:0:TNCCAAGGGT+AAAGGTAGTA
GNCATATGCTCTCAGCCTCAGCCCGGCTGCGGTTGGCAATATCCTCGTACTGTGCCTTGACCTCAGCAATGATGCTGTCCATGTCCAGGGAGCGGCTGTTGTCCATGGACAGCACCACAGATGTGTCCGAGATCTGGGACTGCAGCTCCC
+
I#III9IIIIIIIIIIIIIIIIIIIIIIIIII9I9II9I-II99999999IIIIIIIIIIIIIIIIIIIII-IIIIIIIIIIIIII9IIIII9II9IIIIIIIIIIIIIIIIII9IIIIIIIII9IIIIIIIIIIIIIIII9IIIIIIII

[s208205@Nucleus004 01.RawData]$ zcat mRNA-SI_TT_A7_22TFMKLT3_S3_L008_R1_001.fastq.gz | awk '(NR%4==2) && /TTTCTTATATGGG/' | head
CNGCAACAGAAACTAGCAGACGAGGGGGTTTCTTATATGGGGCTTCTCGCCTAACGCTGCCAACATGGTGTTCAGGCGCTTCGTGGAGGTTGGCCGGGTGGCCTATGTCTCCTTTGGATCTCATGCCGGAAAATTGGTCGCGATTGTAGA
GNCATGCAGCACCTCCGTTTATAGCTATTTTCTTATATGGGGAGCTCCGGCCGCGGAGTGATGGTGGCCTCAGCGAAGATGGGCCGGGCAGGGACCATGGCGGTGGCAGCAGAGGTGGCAGGGGCGGGGCGGCTGGCGGTAGAGGAGGGT
CNATTAGAGCTATGTGCTAAGGTGCTCGTTTCTTATATGGGTTTAGCTAAAACCAAAACAAAAAGCAAGTTGGTACTCAAGTATAACCCCTAATACTGCAAATATTAAGCTACAGGTTCTCTCTTGCCATCTGAAACGTCAGCTATTCAG
TNATATATCATAGTGTCCTGCAATTGGTTTTCTTATATGGGAGGCTCCTGTCCTGAGTGCCAGTCGGCCGGCCCCTTTGAGGTCAACATGGAGGAGACCATCTATCAGAACTACCAGCGTATCCGAATCCAGGAGAGTCCAGGCAAAGTG
CNGGATCTCATGAAAGGGATCTCGCGGCTTTCTTATATGGGAAAATTACCCACTCCCGACCCGGGGAGGTAGTGACGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATACCCTTCGTTGACCCCCCCGAGCTCGGAAAAACACACGTCTG
ANTGTATCACCAGATTGCTCAACGTCAGTTTCTTATATGGGGTATTTCCTGGGTGGGGTTTTTGAAGTCGTGGCCCGTTAGCAGGAAGCATAACAGTCGCCCCGACGCTAGTGAGGGACCCAATCTGAGTCCCCGGCCAGCCGAATCCAA
ANAGGGAGTATCTGTTCCTCGACCAGCCTTTCTTATATGGGGCGGCCCAAGCGGTTTCAAACGGCTTAGAGCCGGCCGCTTGGTTCTGACCAAGCTGAGGAAATACTATTAATTCTAAGGAAAACCTGGAAGCACAATGGGAGATGACAG
CNTAGGGCACTAATATGACGATCCGGGGTTTCTTATATGGGGCTTCTGTCTGGTTCTCTCTCTCCAGAAGGTTCTGCCGGTTCCCCCAGCTCTGGGTACCCGGCTCTGCATCGCGTCGCCATGATGGGCCATCGTCCAGTGCTCGTGCTC
GNCTGATAGCTATGGCTCCGTGCCTTTATTTCTTATATGGGGACCTCGCTTCTTCTCTCCCGGCCGAGGCCCGGGGGACCAGAGCGAGAAGCGGGGACCATGTTCCGACGCAAGTTGACGGCTCTCGACTACCACAACCCCGCCGGCTTC
GNTGATGAGATTCGATCCGGCTTATTAGTTTCTTATATGGGATAGGTTTGGTCCTAGCCTTTCTATTAGCTCTTAGTAAGATTACACATGCAAGCATCCCCGTTCCAGTGAGTTCACCCTCTAAATCACCACGATCAAAAGGGACAAGCA

zcat mRNA-SI_TT_A7_22TFMKLT3_S3_L008_R2_001.fastq.gz | head


[s208205@Nucleus004 01.RawData]$ zcat mRNA-SI_TT_A7_22TFMKLT3_S3_L008_I1_001.fastq.gz | head
@LH00328:476:22TFMKLT3:8:1101:41438:1032 1:N:0:TNCCAAGGGT+AAAGGTAGTA
TNCCAAGGGT
+
9#999IIIII
@LH00328:476:22TFMKLT3:8:1101:42214:1032 1:N:0:TNCCAAGGGT+AAAGGTAGTA
TNCCAAGGGT
+
I#9IIIIIII
@LH00328:476:22TFMKLT3:8:1101:43435:1032 1:N:0:TNCCAAGGGT+AAAGGTAGTA
TNCCAAGGGT

# bash script for PAIR-perturb-seq at BioHPC
# COMMAND GROUP 1
cd /project/pathology/SiZhang_lab/shared/Active_Projects/UTSW24_CC_PAIR_perturb/03.CR8/BioHPC.files


# COMMAND GROUP 2
bash UTSW24_PAIR_perturb.sh



# recover reads from Undertemined fastq files. 
cd /project/pathology/SiZhang_lab/shared/Active_Projects/UTSW24_CC_PAIR_perturb/01.RawData/Undetermined
zcat Undetermined_Undetermined_22TFMKLT3_L8_1.fq.gz | awk '(NR%4==2) && /TTTCTTATATGGG/' | head

python extract_paired_reads.py \
    -r1 Undetermined_Undetermined_22TFMKLT3_L8_1.fq.gz \
    -r2 Undetermined_Undetermined_22TFMKLT3_L8_2.fq.gz \
    -o1 mRNA-SI_TT_A7_matching_reads_R1.fastq.gz \
    -o2 mRNA-SI_TT_A7_matching_reads_R2.fastq.gz \
    -s TTTCTTATATGGG

(ISS) [s208205@Nucleus005 Undetermined]$ zcat matching_reads_R1.fastq.gz | head -n40
@LH00328:476:22TFMKLT3:8:1101:41086:1032 1:N:0:ANTATCTGCA+GGGGGGGGGG
CNCTTGCTCCGCAGCAGACAGTAGGGCCTTTCTTATATGGGAAAATAACCCTGGCAGGAAAGACAATTGACTCAGCTGTCTCTTATACACATCTCCGAGCCCACGAGACAGTATCTGCAATCTGGGGGGGGGGGGTGGGGTTGGTGGGGG
+
I#IIIIIIIIIIIIIIIIIIIIIIIIIII99--I--9-9IIIIII9II9II9IIII9IIII9IIII9III9IIIII9IIIII9IIIIIIIIIIIII-I99IIIIIIIIII-I-IIIIIII-IIIIIIII--I9II---I-9--9--9-9I
@LH00328:476:22TFMKLT3:8:1101:41696:1032 1:N:0:ANTATCTGCA+GGGGGGGGGG
ANTCCCATCAACCCTTGACACAAGCAGTTTTCTTATATGGGGCCCCAACACTGGCAGGAAAGACAGAAGCCCCCCCTGTCTCTTATACACATCTCCGAGCCCACGAGACAGTATCTGCAATCTGGGGGGGGGGGGGTGGGGTTGGGGGGG
+
I#IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IIIIIIIIIII9II---9------99I
@LH00328:476:22TFMKLT3:8:1101:41918:1032 1:N:0:CNTATCTGCA+TCGCTAGCGA
CNCTTGCTCCGCAGCATGTATCGAAGTCTTTCTTATATGGGGCACGTTCCCTGGCAGGAAAGACACCGCCACTTTCTGTCTCTTATACACAGTTCCGAGCCCAAGAGACAGTATCTGCAATCTGGGGGGGGGGGGGTGTGTTATTCTGGA
+
I#III9IIIIII-IIIIIIIIIII9IIIIII-II9I9-I-9I9III9II9III-I9--9IIII-II9IIII9IIII9I-III9I9-9I9999-999I99-III-II9-II-99-I----9-I9------99-9I-I-9---I-99----9
@LH00328:476:22TFMKLT3:8:1101:44174:1032 1:N:0:ANTATTGGAA+TCGCTAGCGA
ANTCCCATCAACCCTTCGAGGTGGATACTTTCTTATATGGGCGGCCCTATCTGGCAGGAAAGACACGCCGCCCCACTGTCTCTTATACACATCTCCGAGCCCACGAGACAGTATTGCAATCTGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
I#IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IIIIII9I-II9I--9I9---99II9-
@LH00328:476:22TFMKLT3:8:1101:44193:1032 1:N:0:ANTATCTGCA+GGGGGGGGGG
GNGTGTAAGACAAGTAAAATTTTCCACCTTTCTTATATGGGATCAGGACCCTGGCAGGAAAGACAAAAAATATCTCTGTCTCTTATACACATCTCCGAGCCCACGAGACAGTATCTGCAATCTGGGGGGGGGGGGGGTGTTTTTGTTGGG
+
I#IIIII9IIIIIIIIIIIIIIIIIIIII-IIIIIIIIIIIIIIIIIIIIIIIIII9I9IIIIIIIIIIIIIIIIIIIIIIII9IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII-IIIIIII-999-I-9I9-I-9I-I99--99
@LH00328:476:22TFMKLT3:8:1101:44803:1032 1:N:0:ANTATCTGCA+GGGGGGGGGG
CNTCGGTTCATGCTTCTAGTTCGCGCATTTTCTTATATGGGCCCTCCGCGCTGGCAGGAAAGACACCCCCCCCGCCTGTCTCTTATACACATCTCCGAGCCCACGAGACAGTATCTGCAATCTGGGGGGGGGTGGGGGGGTGGTTGGGGG
+
I#IIIIIIIIIIIIIIIIIII9IIIIIIIIIIII9IIIIIIIIIIIIIIIIIIIIIIIIIIII99-9IIIIIIIIII9IIIIII-I9IIII-9IIIIII-9IIII9III--I99IIIIIIIIIIIII9IIII-9-99-9I-9--9I9-II
@LH00328:476:22TFMKLT3:8:1101:45468:1032 1:N:0:ANTATCTGCA+AAAGGTAGTA
CNCTGCACAAAGTACGTTCACACTCCACTTTCTTATATGGGTAACACATACTGGCAGGAAAGACATACGACGCTTCTGTCTCTTATACACATCTCCGAGCCCACGAGACAGTATCTGCAATCTGGGGGGGGGGGGGGTTGGTTTTGGGGG
+
I#IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII-IIIII-IIIIIIIIIIIIIIIIII9IIIIIIIIIIIIII9IIIIIII9II99I-IIIIIIIIIIII9I9I99I999I---99-----999--9---9
@LH00328:476:22TFMKLT3:8:1101:45487:1032 1:N:0:ANTATCTTGC+TCGCTAGCGA
ANTCCCATCAACCCTTCCTACAATACTTTTTCTTATATGGGAAGATGTTGCTGGCAGGAAAGACATCCGCGGTACCTGTCTCTTATACACATCTCCGAGCCCACGAGACAGTATCTTGCAATCTGGGGGGGGGGGGGGGGGGGGGGGGGG
+
I#IIIIIIIIIIIIIIIIIIIIIIIIIIIII9IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IIIIIIIIIIII9IIIIIIIIIIIIIIIIIIIIIIII9IIIIIIIIIIIIII-III---II-II9
@LH00328:476:22TFMKLT3:8:1101:45912:1032 1:N:0:ANTATCGTAA+TCGCTAGCGA
CNAGGCCCACGCATATCTACCGCCAGAGTTTCTTATATGGGCCCCGTCCCCTGGCAGGAAAGACAAACCTTAAACCTGTCTCTTATACACATCTCCGAGCCCACGAGACAGTATCGCAATCTGGGGGGGGGGGGGTGGTGGTTTGGGGGG
+
I#IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IIIIIIIIIIIIIIIIIIIIIIIII-IIIIIIIIIIIIIIIIIIIIII9IIIIII9II-I9I-----9-99----99I
@LH00328:476:22TFMKLT3:8:1101:46227:1032 1:N:0:ANTATCTGCA+GGGGGGGGGG
GNTAGTTGTATTGGTACCTGCGGGTGCATTTCTTATATGGGCTACACATTCTGGCAGGAAAGACACCCTGAACAACTGTCTCTTATACACATCTCCGAGCCCACGAGACAGTATCTGCAATCTGGGGGGGGGGGGGGGGTGTGGGGGGGG
+
I#IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IIIII9I9IIIIIII-III99-999-9II

# extract from UTSW25 DDR
cd /project/pathology/SiZhang_lab/shared/Active_Projects/UTSW25_CC_DDR/RAW/01.RawData/Undetermined
zcat Undetermined_Undetermined_22TFMKLT3_L7_1.fq.gz | awk '(NR%4==2) && /TTTCTTATATGGG/' | head
(ISS) [s208205@Nucleus005 Undetermined]$ zcat Undetermined_Undetermined_22TFMKLT3_L7_1.fq.gz | awk '(NR%4==2) && /TTTCTTATATGGG/' | head
GCGTCTACAATCCTAACTCATCTCGGACTTTCTTATATGGGCCGCTCGTCCTGGCAGGAAAGACAACTCACTATTCTGTCTCTTATACACATCTCCGAGCCCACGAGACAGTATCTGCAATCTGGGGGGGGGGGGGGGGGGGGGGGGGGG
CCACAATCAAACATTTTGATCTCCGCTTTTTCTTATATGGGCACGCACCCCTGGCAGGAAAGACACCCGGAACTTCTGTCTCTTATACACATCTCCGAGCCCACGAGACAGTATCTGCAATCTGGGGGGGGGGGGGGGGGGGGGGGGGGG
CGGATTCAGCGTGTTATCGGTTTCGGGCTTTCTTATATGGGGTCTCTTCCTGCTCTCCATCATGGCGCAGGATCAAGGTGAAAAGGAGAACCCCATGCGGGAACTTCGCATCCGCAAACTCTGTCTCAACATCTGTGTTGGGGAGAGTGG
CGGATTCAGCGTGTTATCGGTTTCGGGCTTTCTTATATGGGGTCTCTTCCTGCTCTCCATCATGGCGCAGGATCAAGGTGAAAAGGAGAACCCCATGCGGGAACTTCGCATCCGCAAACTCTGTCTCAACATCTGTGTTGGGGAGAGTGG
CGCTTGCTCCGCAGCACTGCTTCCTCGCTTTCTTATATGGGCCAATGCCCCTGGCAGGAAAGACACCACACCGACCTGTCTCTTATACACATCTCCGAGCCCACGAGACAGTATCTGCAATCGGGGGGGGGGGGGGGGGGGGGGGGGGGG
GGTAGTTGTATTGGTACTACGATTAGCTTTTCTTATATGGGCCCCTGGCCCTGGCAGGAAAGACAGCAGTTATATCTGTCTCTTATACACATCTCCGAGCCCACGAGACAGTATCTGCAATTGGGGGGGGGGGGGGGGGGGGGTGGGGGG
CTAGCCCTCCCTACATCCCGCTCCGCTGTTTCTTATATGGGGGCCAGGCCCAGGGCAGGCGACCCGAGGGCCGAGGGTTTGGAACTCGCAGAGGTTAAACACTTTAAGATGAGAAAAATTGATCTCTGTCTGAGCTCTGAAGGGTCCGAA
CCACAATCAAACATTTTGGCGTTCACGTTTTCTTATATGGGCGCACCTATCTGGCAGGAAAGACATTCCATTGCGCTGTCTCTTATACACATCTCCGAGCCCACGAGACAGTATCTGCAATCTGGGGGGGGGGGGGGGGGGTGGGGGGGG
AGTTACCCACGCGCATGGTGACAGTAGATTTCTTATATGGGCCTTCCCCCCTGGCAGGAAAGACATATGCAGCACCTGTCTCTTATACACATCTCCGAGCCCACGAGACAGTATCTGCAATCTGGGGGGGGGGGGGGGGGGGGGGGGGGG
TGACGGCTCGGTCTAATGTCGAGTTCTTTCTTATATGGGTGACATACTTATACGGGCTCGCTACTATTCTTGCCTGTCTCTTATACACATCTCCGAGCCCACGAGACGACCGCCTTTATCTGGGGGGGAGTGTTGTGGGTGGAAGGGGGG

python extract_paired_reads.py \
    -r1 Undetermined_Undetermined_22TFMKLT3_L7_1.fq.gz \
    -r2 Undetermined_Undetermined_22TFMKLT3_L7_2.fq.gz \
    -o1 UTSW25_mRNA-SI_TT_A7_matching_reads_R1.fastq.gz \
    -o2 UTSW25mRNA-SI_TT_A7_matching_reads_R2.fastq.gz \
    -s TTTCTTATATGGG


####========= PAIR reads extraction and matrix generation =========######

####========= Step 1 extract PAIR elements from PAIR reads =========#####
zcat PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R1_001.fastq.gz | head -n 8000 | gzip > PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R1_001_8000.fastq.gz
zcat PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R2_001.fastq.gz | head -n 8000 | gzip > PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R2_001_8000.fastq.gz

(ISS) [s208205@Nucleus004 PAIR]$ zcat PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R1_001.fastq.gz | awk '(NR%4==2) && /TTTCTTATATGGGGGTAGAAAACACCGAAGTGCG/' | head
ANTATAGCAGTCTGCACCGGTAAGGCGTTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCAAACATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
ANCGGCCTCCTCTGCAGTGTAGCTCGCGTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCAACCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
ANAACCTCAGGACCGACAGCCCGGGGGTTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCAACCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
GNAGATTTCCCCTTAGTGTCGCGACGGGTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCAACCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
GNATCCGAGATTACCGGTTAGGTCAGTCTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCAACCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA

# test extraction logic and script for 2000 reads
python 01_Extract_PAIR.py   --input_r1 PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R1_001_8000.fastq.gz \
                            --input_r2 PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R2_001_8000.fastq.gz \
                            --output_r1 PAIR_matched_R1.fastq.gz \
                            --output_r2 PAIR_matched_R2.fastq.gz \
                            --output_table PAIR_matched_extracted_data_table.txt

zcat PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R1_001.fastq.gz | head -n 200000 | gzip > PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R1_001_200000.fastq.gz
zcat PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R2_001.fastq.gz | head -n 200000 | gzip > PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R2_001_200000.fastq.gz

python 01_Extract_PAIR.py   --input_r1 PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R1_001_200000.fastq.gz \
                            --input_r2 PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R2_001_200000.fastq.gz \
                            --output_r1 PAIR_matched_R1_200000.fastq.gz \
                            --output_r2 PAIR_matched_R2_200000.fastq.gz \
                            --output_table PAIR_matched_extracted_data_table_200000.txt

[s208205@Nucleus024 PAIR]$ zcat PAIR_matched_R1_200000.fastq.gz | awk '(NR%4==2) && /TTTCTTATATGGGG/' | head -n 100
ANTATAGCAGTCTGCACCGGTAAGGCGTTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCAAACATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
ANCGGCCTCCTCTGCAGTGTAGCTCGCGTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCAACCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
GNAGATTTCCCCTTAGTGTCGCGACGGGTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCAACCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
GNATCCGAGATTACCGGTTAGGTCAGTCTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCAACCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA
ANCATAACAAATCTCACCTCACAGGGATTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCAACCATGTCTGCAGGGCCTAGCAAGTTAAAATATAAGGCTAGTCCGTTATCAACTTGGCC
ANCGCAGGTGGCATATTAGGCGAGGTGGTTTCTTATATGGGGGTAGAAAACACCGAAGTGCGGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAA


# PAIR_perturb_whitelist_withID.csv
# ID	            CRISPRa	                CRISPRa_name	CasRx	                CasRx_name
# PAIR_Perturb_21	CTCAGCCAGTTGGCCTGCCA	NT_CRISPRa	    GATGTCATGCGTACGGGATAATC	NT_CasRx
# PAIR_Perturb_22	GTAGAAAACACCGAAGTGCG	POLD3_CRISPRa	CACATACACAAATGTGTGCACGT	PKcs-1_CasRx
# PAIR_Perturb_23	GTAGAAAACACCGAAGTGCG	POLD3_CRISPRa	GATGTCATGCGTACGGGATAATC	NT_CasRx
# PAIR_Perturb_24	GTCAGCCAGTTGGCCTGCCA	NT_CRISPRa	    CACATACACAAATGTGTGCACGT	PKcs-1_CasRx

[s208205@Nucleus024 PAIR]$ head PAIR_matched_extracted_data_table_200000.txt
CellBC  UMI     CRISPRa_gRNA    CasRx_crRNA
ANTATAGCAGTCTGCA        CCGGTAAGGCGT    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC
ANCGGCCTCCTCTGCA        GTGTAGCTCGCG    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC
GNAGATTTCCCCTTAG        TGTCGCGACGGG    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC
GNATCCGAGATTACCG        GTTAGGTCAGTC    GTAGAAAACACCGAAGTGCG    CACATACACAAATGTGTGCACGT
ANCATAACAAATCTCA        CCTCACAGGGAT    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC
ANCGCAGGTGGCATAT        TAGGCGAGGTGG    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC
GNATAGTGTGTGCGGT        CCCGGTTTGGAG    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC
GNTAAGACAAGGTTAG        TATTCTAGTGCC    TAGAAAACACCGAAGTGCGG    GATGTCATGCGTACGGGATAATC
GNCACTCCAAGTCGCC        TTCGACCTGGGT    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC

[s208205@Nucleus024 PAIR]$ awk 'NR > 1 {print $3}' PAIR_matched_extracted_data_table_200000.txt | sort | uniq -c | sort -nr | head
  10611 GTAGAAAACACCGAAGTGCG
   1580 TAGAAAACACCGAAGTGCGG
    228 GTCAGCCAGTTGGCCTGCCA
    211 CTCAGCCAGTTGGCCTGCCA
    206 GGTAGAAAACACCGAAGTGC
    106 AGGATCACCCATGTCTGCAG
     62 TCAGCCAGTTGGCCTGCCAG
     36 GTAGAAAACACCGAAGTACG
     27 GGGTAGAAAACACCGAAGTG
     26 ACCGGTAGAAAACACCGAAG

[s208205@Nucleus024 PAIR]$ awk 'NR > 1 {print $4}' PAIR_matched_extracted_data_table_200000.txt | sort | uniq -c | sort -nr | head
  11095 GATGTCATGCGTACGGGATAATC
   2267 CACATACACAAATGTGTGCACGT
     46 GATGTTATGCGTACGGGATAATC
     17 CAAGTGGCACCGAGTCGGTGCTT
     16 GATGGCATGCGTACGGGATAATC
     11 GATGTCATGCGTACGGGATAAGC
     10 GATGTCATGCATACGGGATAATC
      8 GATGTCATGCGTACGGAATAATC
      7 GATGTCATGCGTATGGGATAATC
      5 GATGTCATACGTACGGGATAATC

# full run
python 01_Extract_PAIR.py   --input_r1 PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R1_001.fastq.gz \
                            --input_r2 PAIR-SI_TT_A6_22TFMKLT3_S2_L008_R2_001.fastq.gz \
                            --output_r1 PAIR_matched_R1.fastq.gz \
                            --output_r2 PAIR_matched_R2.fastq.gz \
                            --output_table PAIR_matched_extracted_data_table.txt

# PAIR_perturb_whitelist_withID.csv
# ID	            CRISPRa	                CRISPRa_name	CasRx	                CasRx_name
# PAIR_Perturb_21	CTCAGCCAGTTGGCCTGCCA	NT_CRISPRa	    GATGTCATGCGTACGGGATAATC	NT_CasRx
# PAIR_Perturb_22	GTAGAAAACACCGAAGTGCG	POLD3_CRISPRa	CACATACACAAATGTGTGCACGT	PKcs-1_CasRx
# PAIR_Perturb_23	GTAGAAAACACCGAAGTGCG	POLD3_CRISPRa	GATGTCATGCGTACGGGATAATC	NT_CasRx
# PAIR_Perturb_24	GTCAGCCAGTTGGCCTGCCA	NT_CRISPRa	    CACATACACAAATGTGTGCACGT	PKcs-1_CasRx

(ISS) [s208205@Nucleus005 PAIR]$ awk 'NR > 1 {print $3}' PAIR_matched_extracted_data_table.txt | sort | uniq -c | sort -nr | head
34401495 GTAGAAAACACCGAAGTGCG
4867425 TAGAAAACACCGAAGTGCGG
 686391 GGTAGAAAACACCGAAGTGC
 580747 GTCAGCCAGTTGGCCTGCCA
 507718 CTCAGCCAGTTGGCCTGCCA
 207082 AGGATCACCCATGTCTGCAG
 165085 TCAGCCAGTTGGCCTGCCAG
  86770 ACCGGTAGAAAACACCGAAG
  85759 GGGTAGAAAACACCGAAGTG
  68175 GTAGAAAACACCGAAGTGTG
(ISS) [s208205@Nucleus005 PAIR]$ awk 'NR > 1 {print $4}' PAIR_matched_extracted_data_table.txt | sort | uniq -c | sort -nr | head
35957212 GATGTCATGCGTACGGGATAATC
6674256 CACATACACAAATGTGTGCACGT
 140035 GATGTTATGCGTACGGGATAATC
  55160 GATGTCATGCGTACGGNATAATC
  43027 CAAGTGGCACCGAGTCGGTGCTT
  33055 GATGTCATGCGTACGGGATAAGC
  28452 GATGGCATGCGTACGGGATAATC
  28011 GATGTCATGCGGACGGGATAATC
  27848 GATGTCATGCATACGGGATAATC
  20513 GATGTCATACGTACGGGATAATC

####========= Step 2: CellBC mapping to mRNA filtered CellBC =========#####
(ISS) [s208205@Nucleus004 PAIR]$ head -n 100001 PAIR_matched_extracted_data_table.txt > PAIR_matched_extracted_data_table_100000.txt
(ISS) [s208205@Nucleus004 PAIR]$ head PAIR_matched_extracted_data_table_100000.txt

# test run. sample_filtered_barcodes.csv is the filtered Cell barcode list generated from Cellranger 
python 02_Cellbc_Whitelist_Mapping.py \
    --whitelist sample_filtered_barcodes.csv \
    --extracted_data PAIR_matched_extracted_data_table_100000.txt \
    --output PAIR_matched_extracted_data_table_100000_CellBC.mapped.txt \
    --unmapped PAIR_matched_extracted_data_table_100000_CellBC.unmapped.txt \
    --tolerance 2 \
    --k 10 \
    --log_file PAIR_matched_extracted_data_table_100000_CellBC.mapping.log.txt

# mapping with incremental output and log
python 02_Cellbc_Whitelist_Mapping.py \
    --whitelist sample_filtered_barcodes.csv \
    --extracted_data PAIR_matched_extracted_data_table.txt \
    --output PAIR_matched_extracted_data_table_CellBC.mapped.txt \
    --unmapped PAIR_matched_extracted_data_table_CellBC.unmapped.txt \
    --tolerance 2 \
    --k 10 \
    --log_file PAIR_matched_extracted_data_table_CellBC.mapping.log.txt   

(ISS) [s208205@Nucleus005 PAIR]$ tail PAIR_matched_extracted_data_table_CellBC.mapped.txt
GTTCGCACAACTGCGC        TTCAGCCCCGCC    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC GTTCGCACAACTGCGC
CAATGTTAGCACTCCC        AATCAACCTTGC    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC CAATGTTAGCACTCCC
ATCGCCACAACGAAAT        GCTTCTACTCCT    GGGTAGAAAACACCGAAGTG    CACATACACAAATGTGTGCACGT ATCGCCACAACGAAAT
GCAGTCAGTCTTAGTT        CTGTGGGCTAGC    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC GCAGTCAGTCTTAGTT
ACAACCTCAGGACCGA        AGAGCCGAGTTA    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC ACAACCTCAGGACCGA
ATCGCTCGTCACTCCG        GTGCAGTTGGTG    TAGAAAACACCGAAGTGCGG    GATGTCATGCGTACGGGATAATC ATCGCTCGTCACTCCG
AGGTTCGGTGCCACTT        TATAGTTGTGGG    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC AGGTTCGGTGCCACTT
AATGCGCTCCATTCAC        TCTGAAGGCATG    TAGAAAACACCGAAGTGCGG    GATGTCATGCGTACGGGATAATC AATGCGCTCCATTCAC
ATCGAAGCAGCTGTAT        TATTCGTCGCAT    TAGAAAACACCGAAGTGCGG    GATGTCATGCGTACGGGATAATC ATCGAAGCAGCTGTAT
CTAACTACACGTTCGA        TGGGTATTGCAA    GTAGAAAACACCGAAGTGCG    CACATACACAAATGTGTGCACGT CTAACTACACGTTCGA

# PAIR_perturb_whitelist_withID.csv
# ID	            CRISPRa	                CRISPRa_name	CasRx	                CasRx_name
# PAIR_Perturb_21	CTCAGCCAGTTGGCCTGCCA	NT_CRISPRa	    GATGTCATGCGTACGGGATAATC	NT_CasRx
# PAIR_Perturb_22	GTAGAAAACACCGAAGTGCG	POLD3_CRISPRa	CACATACACAAATGTGTGCACGT	PKcs-1_CasRx
# PAIR_Perturb_23	GTAGAAAACACCGAAGTGCG	POLD3_CRISPRa	GATGTCATGCGTACGGGATAATC	NT_CasRx
# PAIR_Perturb_24	GTCAGCCAGTTGGCCTGCCA	NT_CRISPRa	    CACATACACAAATGTGTGCACGT	PKcs-1_CasRx

(ISS) [s208205@Nucleus005 PAIR]$ tail PAIR_matched_extracted_data_table_CellBC.mapped.txt
TACAAGACACTGGGAG        AACAGGGGTCAA    GTAGAAAACACCGAAGTGCG    GATGTCATACGTACGGGATAATC CACAAGACACTGGGAG
CAATGTTAGCACTCCC        TTGCTCCATGGA    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC CAATGTTAGCACTCCC
ATATGGCGTCACCGGG        TGTTAGCCGTCA    TAGAAAACACCGAAGTGCGG    GATGTCATGCGTACGGGATAATC ATATGGCGTCACCGGG
CCACACACAAGTCGGG        TTTACGAACTCC    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC CCACACACAAGTCGGG
ACTGATTAGCCCAAGT        TTGGGGGGTTGC    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC ACTGATTAGCCCAAGT
GTTCGCACAACTGCGC        ATTTTGTGGCTA    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC GTTCGCACAACTGCGC
ATCAGGCTCGTGCAAC        TGTGCGTTGGCT    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC ATCAGGCTCGTGCAAC
AACGAAGGTCAACCTC        ATTACGAGTAGG    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC AACGAAGGTCAACCTC
ATTCGGGGTCGGGTAC        CTACAGCTAGTA    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC ATTCGGGGTCGGGTAC
ATTCGGGGTCGGGTAC        CTACAGCTAGTA    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC ATTCGGGGTCGGGTAC


#####========= Step 3: Mapping PAIR whitelist =========#####
(ISS) [s208205@Nucleus005 PAIR]$ head -n 20001 PAIR_matched_extracted_data_table_CellBC.mapped.txt > PAIR_matched_extracted_data_table_CellBC.mapped_20000.txt
(ISS) [s208205@Nucleus005 PAIR]$ head PAIR_matched_extracted_data_table_CellBC.mapped_20000.txt
CellBC  UMI     CRISPRa_gRNA    CasRx_crRNA     Mapped_CellBC
ANTATAGCAGTCTGCA        CCGGTAAGGCGT    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC AATATAGCAGTCTGCA
GNAGATTTCCCCTTAG        TGTCGCGACGGG    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC GTAGATTTCCCCTTAG
GNATCCGAGATTACCG        GTTAGGTCAGTC    GTAGAAAACACCGAAGTGCG    CACATACACAAATGTGTGCACGT GCATCCGAGATTACCG
ANCATAACAAATCTCA        CCTCACAGGGAT    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC AACATAACAAATCTCA
ANCGCAGGTGGCATAT        TAGGCGAGGTGG    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC ATCGCAGGTGGCATAT
GNATAGTGTGTGCGGT        CCCGGTTTGGAG    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC GCATAGTGTGTGCGGT
GNTAAGACAAGGTTAG        TATTCTAGTGCC    TAGAAAACACCGAAGTGCGG    GATGTCATGCGTACGGGATAATC GCTACCACAAGGTTAG
GNCACTCCAAGTCGCC        TTCGACCTGGGT    GTAGAAAACACCGAAGTGCG    GATGTCATGCGTACGGGATAATC GTCGGTCCAAGTCGCC
ANCCCTCTCCTCATTA        CATTTTGAAGTG    AGGATCACCCATGTCTGCAG    GATGTCATGCGTACGGGATAATC AGGACTCTCCTCATTA

(ISS) [s208205@Nucleus005 PAIR]$ head PAIR_perturb_whitelist_withID.csv
ID,CRISPRa,CRISPRa_name,CasRx,CasRx_name
PAIR_Perturb_21,CTCAGCCAGTTGGCCTGCCA,NT_CRISPRa,GATGTCATGCGTACGGGATAATC,NT_CasRx
PAIR_Perturb_22,GTAGAAAACACCGAAGTGCG,POLD3_CRISPRa,CACATACACAAATGTGTGCACGT,PKcs-1_CasRx
PAIR_Perturb_23,GTAGAAAACACCGAAGTGCG,POLD3_CRISPRa,GATGTCATGCGTACGGGATAATC,NT_CasRx
PAIR_Perturb_24,GTCAGCCAGTTGGCCTGCCA,NT_CRISPRa,CACATACACAAATGTGTGCACGT,PKcs-1_CasRx

## test run
python 03_PAIR_Whitelist_Mapping.py \
    --input PAIR_matched_extracted_data_table_CellBC.mapped_20000.txt \
    --whitelist PAIR_perturb_whitelist_withID.csv \
    --output PAIR_matched_extracted_data_table_CellBC.PAIR.mapped_20000.txt \
    --k 15 \
    --tolerance 2 \
    --log PAIR_matched_extracted_data_table_CellBC.PAIR.mapped_20000.log


(ISS) [s208205@Nucleus005 PAIR]$ awk 'NR > 1 {print $7}' PAIR_matched_extracted_data_table_CellBC.PAIR.mapped_20000.txt | sort | uniq -c | sort -nr | head
  15623 POLD3_CRISPRa_NT_CasRx
   2851 POLD3_CRISPRa_PKcs-1_CasRx
    434 NT_CRISPRa_PKcs-1_CasRx
    322 NT_CRISPRa_NT_CasRxad


# full run
python 03_PAIR_Whitelist_Mapping.py \
    --input PAIR_matched_extracted_data_table_CellBC.mapped.txt \
    --whitelist PAIR_perturb_whitelist_withID.csv \
    --output PAIR_matched_extracted_data_table_CellBC.PAIR.mapped.txt \
    --k 15 \
    --tolerance 2 \
    --log PAIR_matched_extracted_data_table_CellBC.PAIR.mapped.log

(ISS) [s208205@Nucleus005 PAIR]$ awk 'NR > 1 {print $7}' PAIR_matched_extracted_data_table_CellBC.PAIR.mapped.txt | sort | uniq -c | sort -nr | head
12911992 POLD3_CRISPRa_NT_CasRx
2157091 POLD3_CRISPRa_PKcs-1_CasRx
 280260 NT_CRISPRa_PKcs-1_CasRx
 207956 NT_CRISPRa_NT_CasRx

(ISS) [s208205@Nucleus005 PAIR]$ tail PAIR_matched_extracted_data_table_CellBC.PAIR.mapped.txt
AGCTTNCGTGGCTTAG        TCGGCCAACTCT    GTAGAAAACACCGAANTGCG    GATGTCAGGCGTACGGGATAATC AGCTTCCGTGGCTTAG        GTAGAAAACACCGAAGTGCGGATGTCATGCGTACGGGATAATC     POLD3_CRISPRa_NT_CasRx  2
ATCAANGCACGCAGGA        AAAGGGCTTGTA    GTAGAAAACACCGAANTGCG    GATGTCATGCGTACGGGATAATC ATCAAGGCACGCAGGA        GTAGAAAACACCGAAGTGCGGATGTCATGCGTACGGGATAATC     POLD3_CRISPRa_NT_CasRx  1
ATGGTNGTCACAACCA        GTCAGCTTCGCA    GTAGAAAACACCGAANTGCG    CACATACACAAATGTGTGCACGT ATGGTTGTCACAACCA        GTAGAAAACACCGAAGTGCGCACATACACAAATGTGTGCACGT     POLD3_CRISPRa_PKcs-1_CasRx      1
CCTTCNCTCAAGCCTA        CATCCTGTTCGG    GTAGAAAACACCGAANTGCG    GATGTCATGCGTACGGGATAATC CCTTCTCTCAAGCCTA        GTAGAAAACACCGAAGTGCGGATGTCATGCGTACGGGATAATC     POLD3_CRISPRa_NT_CasRx  1
GCCATNATCATGGCAC        TTTAGGCGATGG    GTAGAAAACACCGAANTGCG    CACATACACAAATGTGTGCACGT GCCATAATCATGGCAC        GTAGAAAACACCGAAGTGCGCACATACACAAATGTGTGCACGT     POLD3_CRISPRa_PKcs-1_CasRx      1
GGCTANCCACGAACGG        AGATAATGAGGC    GTAGAAAACACCGAANTGCG    CANATACACAAATGTGTGCACGT GGCTACCCACGAACGG        GTAGAAAACACCGAAGTGCGCACATACACAAATGTGTGCACGT     POLD3_CRISPRa_PKcs-1_CasRx      2
GGCTANCCACGAACGG        AGATAATGAGGC    GTAGAAAACACCGAANTGCG    CANATACACAAATGTGTGCACGT GGCTACCCACGAACGG        GTAGAAAACACCGAAGTGCGCACATACACAAATGTGTGCACGT     POLD3_CRISPRa_PKcs-1_CasRx      2
GGCAANTTCCTATGCT        GCCGATCCAAGG    GTCAGCCAGTTGGCCNGCCA    CANATACACAAATGTGTGCACGT GGCAACTTCCTATGCT        GTCAGCCAGTTGGCCTGCCACACATACACAAATGTGTGCACGT     NT_CRISPRa_PKcs-1_CasRx 2
GTTCGNACAACTGCGC        GGAAGACCAGGG    GTAGAAAACACCGAANTGCG    GNTGTCATGCGTACGGGATAATC GTTGAGACAACTGCGC        GTAGAAAACACCGAAGTGCGGATGTCATGCGTACGGGATAATC     POLD3_CRISPRa_NT_CasRx  2
CTAATNACACATTCGG        ATCTACATTAGT    GTAGAAAACACCGAANTGCG    GANGTCATGCGTACGGGATAATC CTAATCACACATTCGG        GTAGAAAACACCGAAGTGCGGATGTCATGCGTACGGGATAATC     POLD3_CRISPRa_NT_CasRx  2

####========= Step 4: Caculate freq of mapped CellBC and generate UMI matrix =========#####
(ISS) [s208205@Nucleus005 PAIR]$ python 04_Generate_PAIR_UMI_matrix.py \
>     -i PAIR_matched_extracted_data_table_CellBC.PAIR.mapped.txt \
>     -s PAIR_matched_sparse_UMI_matrix \
>     -f PAIR_matched_frequency.txt
2025-01-13 11:40:06,633 - INFO - Starting processing of PAIR_matched_extracted_data_table_CellBC.PAIR.mapped.txt
2025-01-13 11:40:56,070 - INFO - Input file PAIR_matched_extracted_data_table_CellBC.PAIR.mapped.txt loaded successfully with 40064163 rows.
2025-01-13 11:40:56,284 - INFO - Used 'Mapped_name' as the unique gRNA combination.
2025-01-13 11:40:57,664 - INFO - Frequency table saved to PAIR_matched_frequency.txt with 4 rows.
2025-01-13 11:41:31,913 - INFO - Grouped data into 27604 unique (Mapped_CellBC, gRNA_combination) pairs.
2025-01-13 11:41:31,930 - INFO - Pivoted data into a matrix format.
2025-01-13 11:41:31,970 - INFO - Matrix Market file saved to PAIR_matched_sparse_UMI_matrix.mtx
2025-01-13 11:41:31,981 - INFO - Row labels saved to PAIR_matched_sparse_UMI_matrix_rows.txt
2025-01-13 11:41:31,981 - INFO - Column labels saved to PAIR_matched_sparse_UMI_matrix_columns.txt
2025-01-13 11:41:32,015 - INFO - Sparse matrix also saved to PAIR_matched_sparse_UMI_matrix.npz
2025-01-13 11:41:32,015 - INFO - Matrix statistics: 16541 cells, 4 gRNA combinations.
2025-01-13 11:41:32,015 - INFO - Non-zero entries in matrix: 27604

(ISS) [s208205@Nucleus005 PAIR]$ cat PAIR_matched_frequency.txt
Mapped_name     Frequency
POLD3_CRISPRa_NT_CasRx  33236520
POLD3_CRISPRa_PKcs-1_CasRx      5563620
NT_CRISPRa_PKcs-1_CasRx 726924
NT_CRISPRa_NT_CasRx     537099

# PAIR_perturb_whitelist_withID.csv
# ID	            CRISPRa	                CRISPRa_name	CasRx	                CasRx_name      HTO     PAIR Freq
# PAIR_Perturb_21	CTCAGCCAGTTGGCCTGCCA	NT_CRISPRa	    GATGTCATGCGTACGGGATAATC	NT_CasRx        C255    537099
# PAIR_Perturb_22	GTAGAAAACACCGAAGTGCG	POLD3_CRISPRa	CACATACACAAATGTGTGCACGT	PKcs-1_CasRx    C256    5563620
# PAIR_Perturb_23	GTAGAAAACACCGAAGTGCG	POLD3_CRISPRa	GATGTCATGCGTACGGGATAATC	NT_CasRx        C257    33236520
# PAIR_Perturb_24	GTCAGCCAGTTGGCCTGCCA	NT_CRISPRa	    CACATACACAAATGTGTGCACGT	PKcs-1_CasRx    NA      726924

# C255:NT_CRISPRa_NT_CasRx: CTCAGCCAGTTGGCCTGCCAGATGTCATGCGTACGGGATAATC
# C256:POLD3_CRISPRa_PKcs-1_CasRx: GTAGAAAACACCGAAGTGCGCACATACACAAATGTGTGCACGT
# C257:POLD3_CRISPRa_NT_CasRx: GTAGAAAACACCGAAGTGCGGATGTCATGCGTACGGGATAATC


