# in bash load packages
module load python/3.10.x-anaconda 

# activate the conda env. The latest mageck has been installed under ISS env
conda activate ISS 

cd ${PROJECT_ROOT:-.}/RAW/01.RawData/DDR1


# grep target U6 handle sequences on beginning of R1. The pattern is GTGGAAAGGACGAAACACCG + Position 1 (20nt) + GTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAG 

(ISS) [s208205@Nucleus005 DDR1]$ zcat DDR1_CKDL240042575-1A_22TFMKLT3_L7_1.fq.gz | awk '(NR%4==2) && /GTGGAAAGGACGAAACACCG/' | head
ANGTGGAAAGGACGAAACACCGGTGCTGGGTGCTGTTGCCAGGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCAAGTGGCACCGAGTCGGTGCTTCAAGTAAACCCCTACCAACTGGTCGGGGTTTGAAACAGCG
GNAGGTGGAAAGGACGAAACACCGGGGCCTGGGACACTGATGAGGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGT
TNAAGGTGGAAAGGACGAAACACCGTCGGTGCGGCCCATCCCGGAGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATG
TNAAGGTGGAAAGGACGAAACACCGGGTCAAACTAGTCAGGGAGAGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATG
GNAGGTGGAAAGGACGAAACACCGGACCCTAACCAGGATCCTGCGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGT
TNAAGGTGGAAAGGACGAAACACCGGGCTTGCGCAGTGTCGACGCGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATG
TNAAGGTGGAAAGGACGAAACACCGACTTTCCCGGGGACCCCTGCGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATG
ANGTGGAAAGGACGAAACACCGGACCCTAACCAGGATCCTGCGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGTCT
ANGTGGAAAGGACGAAACACCGCATGCGCATCCAGTATCACGGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGTCT
GNAGGTGGAAAGGACGAAACACCGGGCGCTTGCCCGCCACCTGGGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGT

# grep R2 with handle at beginning of the reads TGACCGCTGAAGTACAAGTGGTAGAGTAG. The pattern is: TGACCGCTGAAGTACAAGTGGTAGAGTAG + BC(14nt) + A(7nt) + Position 2 RC (23nt) + GTTTCAAACCCC
(ISS) [s208205@Nucleus005 DDR1]$ zcat DDR1_CKDL240042575-1A_22TFMKLT3_L7_2.fq.gz | awk '(NR%4==2) && /TGACCGCTGAAGTACAAGTGGTAGAGTAG/' | head
TGACCGCTGAAGTACAAGTGGTAGAGTAGATAGACGTCTTGAGAAAAAAACAGGCCTTCTTACTTTATTCGCTGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGCACGTGTATTCACGAAAAAAACCTGGCTACTAAATATTTTATGTGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGAATAGCACAGGTGCAAAAAAATCTGGCAGTCTCATTCAGAATGGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGGCACTGTATACTTGAAAAAAATGCAGCAGCAATCTTGACTTCTGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGGTTCTTCTGGAGGAAAAAAAAAGTCTGTCACAAAGTCTATTCTGAGTTTCAAACCCCGACCAGTTGGTAGGGGTTTCCTTGAAGCACCGACTCGGTGTCACTTTGCCCCTCCGACACGGGT
TGACCGCTGAAGTACAAGTGGTAGAGTAGCTCTCGTGAAGTGAAAAAAAAGGCTGTGCTAAATAATGTCATTTGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGTAGGTAGCTATTGCAAAAAAATCTCGGGAAGCAGCTGTGGAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGTTCTTCGAAGCATCAAAAAAATGGGGGTGATATGAAAGAGTGGTGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGCATAGTGACCATCAAAAAAAACAGGGCAAGCACTTCTTTCTTTAGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGCACGATATACGCGTAAAAAAAGTGCCTTGGACATTTTAAGTTGTGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG

# QC
fastp \
  -i DDR1_CKDL240042575-1A_22TFMKLT3_L7_1.fq.gz \
  -I DDR1_CKDL240042575-1A_22TFMKLT3_L7_2.fq.gz \
  -o DDR1_CKDL240042575-1A_22TFMKLT3_L7_out1.fq.gz \
  -O DDR1_CKDL240042575-1A_22TFMKLT3_L7_out2.fq.gz \
  --html DDR1_CKDL240042575-1A_22TFMKLT3_L7_fastp.html \
  --json DDR1_CKDL240042575-1A_22TFMKLT3_L7_fastp.json

# extraction and freq calculations
python UTSW25_DDR_BC_extraction.py -r1 DDR1_CKDL240042575-1A_22TFMKLT3_L7_1.fq.gz -r2 DDR1_CKDL240042575-1A_22TFMKLT3_L7_2.fq.gz -o DDR1_extraction_output.txt -l DDR1_extraction_output.log -p 100000
python calculate_frequencies.py -i DDR1_extraction_output.txt -o DDR1_unique_combinations_sorted.txt -v

# DDR2
cd ${PROJECT_ROOT:-.}/RAW/01.RawData/DDR2

(ISS) [s208205@Nucleus005 DDR2]$ zcat DDR2_CKDL240042575-1A_22TFMKLT3_L7_1.fq.gz | awk '(NR%4==2) && /GTGGAAAGGACGAAACACCG/' | head
ANGGTGGAAAGGACGAAACACCGCTCATCCAAGGCAGCCTGCGGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGTC
TNAAGGTGGAAAGGACGAAACACCGACACTGAGAAATACCCGCAGGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATG
TNAAGGTGGAAAGGACGAAACACCGCCAGTCGCGCCTCTCCAGAGGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATG
GNAGGTGGAAAGGACGAAACACCGGCAGCCAGGCTCGCGATGGGGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGT
GNAGGTGGAAAGGACGAAACACCGCGCCAAGCAGCCGCAGAGCAGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGT
GNAGGTGGAAAGGACGAAACACCGTCGGTGCGGCCCATCCCGGAGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGT
GNAGGTGGAAAGGACGAAACACCGTCTTAACCGCCCGTCTTGGTGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGT
GNAGGTGGAAAGGACGAAACACCGTCAGGATTGGCTCCTGCGTAGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGGATCACCCATG
TNAAGGTGGAAAGGACGAAACACCGGAGGAGCGCCCCAGTGGCCAGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATG
ANGTGGAAAGGACGAAACACCGCAGGACGCAACCCTATGAGTGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGTCT

(ISS) [s208205@Nucleus005 DDR2]$ zcat DDR2_CKDL240042575-1A_22TFMKLT3_L7_2.fq.gz | awk '(NR%4==2) && /TGACCGCTGAAGTACAAGTGGTAGAGTAG/' | head
TGACCGCTGAAGTACAAGTGGTAGAGTAGTGGTGAACTGACGTAAAAAAATGCAGCAGCAATCTTGACTTCTGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGACACTCGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGGTATCGATACATCCAAAAAAACTTGGATGCATTTTTCTCTTTGTGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGTTGAGATCACAGTGAAAAAAAGCTGAGGCAGCTAAATTAGTTCCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGCCTCCAATAATGGTAAAAAAATCCTGGCTACTAAATATTTTATGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGAGGTAACCTAGGTGAAAAAAACGTGCTCTCCTCTCTTTTGGTGGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGTGTTCGCAGGACTGAAAAAAAATTGGATGCATTTTTCTCTTTGTGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGTACTATCAGCCGCGAAAAAAATGCAGCAGCAATCTTGACTTCTGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGTTCGCACCACTTGTAAAAAAAAGGCTGTGCTAAATAATGTCATTTGTTTCAAACCCTGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGT
TGACCGCTGAAGTACAAGTGGTAGAGTAGCTGGAGCTCTCTAAAAAAAAAAACCTGTCCAAAGACGACTTGATAGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGT
TGACCGCTGAAGTACAAGTGGTAGAGTAGCGTCCATCAACGAAAAAAAAACCTGGCTGCTACTGTTCCATGGGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAACACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG

# QC
fastp \
  -i DDR2_CKDL240042575-1A_22TFMKLT3_L7_1.fq.gz \
  -I DDR2_CKDL240042575-1A_22TFMKLT3_L7_2.fq.gz \
  -o DDR2_CKDL240042575-1A_22TFMKLT3_L7_out1.fq.gz \
  -O DDR2_CKDL240042575-1A_22TFMKLT3_L7_out2.fq.gz \
  --html DDR2_CKDL240042575-1A_22TFMKLT3_L7_fastp.html \
  --json DDR2_CKDL240042575-1A_22TFMKLT3_L7_fastp.json

# extract position sequences and calcualte frequencies for all samples
python UTSW25_DDR_BC_extraction.py -r1 DDR2_CKDL240042575-1A_22TFMKLT3_L7_1.fq.gz -r2 DDR2_CKDL240042575-1A_22TFMKLT3_L7_2.fq.gz -o DDR2_extraction_output.txt -l DDR2_extraction_output.log -p 100000
python calculate_frequencies.py -i DDR2_extraction_output.txt -o DDR2_unique_combinations_sorted.txt -v

python UTSW25_DDR_BC_extraction.py -r1 DDR3_CKDL240042575-1A_22TFMKLT3_L7_1.fq.gz -r2 DDR3_CKDL240042575-1A_22TFMKLT3_L7_2.fq.gz -o DDR3_extraction_output.txt -l DDR2_extraction_output.log -p 100000
python calculate_frequencies.py -i DDR3_extraction_output.txt -o DDR3_unique_combinations_sorted.txt -v

python UTSW25_DDR_BC_extraction.py -r1 DDR4_CKDL240042575-1A_22TFMKLT3_L7_1.fq.gz -r2 DDR4_CKDL240042575-1A_22TFMKLT3_L7_2.fq.gz -o DDR4_extraction_output.txt -l DDR2_extraction_output.log -p 100000
python calculate_frequencies.py -i DDR4_extraction_output.txt -o DDR4_unique_combinations_sorted.txt -v

python UTSW25_DDR_BC_extraction.py -r1 DDR5_CKDL240042575-1A_22TFMKLT3_L7_1.fq.gz -r2 DDR5_CKDL240042575-1A_22TFMKLT3_L7_2.fq.gz -o DDR5_extraction_output.txt -l DDR2_extraction_output.log -p 100000
python calculate_frequencies.py -i DDR5_extraction_output.txt -o DDR5_unique_combinations_sorted.txt -v

# map the frequencies to the whitelist
python All_positions_mapping.py --input_file DDR1_unique_combinations_sorted.txt \
                                 --whitelist_file ${PROJECT_ROOT:-.}/Sub_info/Final_oligos_withID.csv \
                                 --output_file DDR1_unique_combinations_sorted_mapped.txt


# mapping with kmer tolerance
awk '$4 >= 20' DDR1_unique_combinations_sorted.txt > DDR1_unique_combinations_sorted_filtered.txt

python kmer-mapping.py --input_file DDR1_unique_combinations_sorted_filtered.txt \
                        --whitelist_file Whitelist_withID.csv \
                        --output_file DDR1_unique_combinations_sorted_mapped_output_kmerHD1.csv \
                        --tolerance 1

python Final_collapse_HD1.py DDR1_unique_combinations_sorted_mapped_output_kmerHD1.csv Whitelist_withID.csv DDR1_Final_kmer_mapped_count_HD1.csv

# all in one script
python 01_Mapping.py --input_file DDR1_unique_combinations_sorted.txt \
                     --whitelist_file Whitelist_withID.csv \
                     --output_file DDR1_Final_kmer_mapped_count_HD1_T100.csv \
                     --tolerance 1 \
                     --count_threshold 100

python 01_Mapping.py --input_file DDR1_unique_combinations_sorted.txt \
                     --whitelist_file Whitelist_withID.csv \
                     --output_file DDR1_Final_kmer_mapped_count_HD1_T50_kmer20.csv \
                     --tolerance 1 \
                     --count_threshold 50

# repeat for DDR2, DDR3, DDR4, DDR5
python All_positions_mapping.py --input_file DDR2_unique_combinations_sorted.txt \
                                 --whitelist_file ${PROJECT_ROOT:-.}/Sub_info/Final_oligos_withID.csv \
                                 --output_file DDR2_unique_combinations_sorted_mapped.txt

python 01_Mapping.py --input_file DDR2_unique_combinations_sorted.txt \
                     --whitelist_file Whitelist_withID.csv \
                     --output_file DDR2_Final_kmer_mapped_count_HD1_T100.csv \
                     --tolerance 1 \
                     --count_threshold 100

python 01_Mapping.py --input_file DDR2_unique_combinations_sorted.txt \
                     --whitelist_file Whitelist_withID.csv \
                     --output_file DDR2_Final_kmer_mapped_count_HD1_T50_kmer20.csv \
                     --tolerance 1 \
                     --count_threshold 50

python All_positions_mapping.py --input_file DDR3_unique_combinations_sorted.txt \
                                 --whitelist_file ${PROJECT_ROOT:-.}/Sub_info/Final_oligos_withID.csv \
                                 --output_file DDR3_unique_combinations_sorted_mapped.txt

python 01_Mapping.py --input_file DDR3_unique_combinations_sorted.txt \
                     --whitelist_file Whitelist_withID.csv \
                     --output_file DDR3_Final_kmer_mapped_count_HD1_T100.csv \
                     --tolerance 1 \
                     --count_threshold 100

python 01_Mapping.py --input_file DDR3_unique_combinations_sorted.txt \
                     --whitelist_file Whitelist_withID.csv \
                     --output_file DDR3_Final_kmer_mapped_count_HD1_T50_kmer20.csv \
                     --tolerance 1 \
                     --count_threshold 50                    

python All_positions_mapping.py --input_file DDR4_unique_combinations_sorted.txt \
                                 --whitelist_file ${PROJECT_ROOT:-.}/Sub_info/Final_oligos_withID.csv \
                                 --output_file DDR4_unique_combinations_sorted_mapped.txt

python 01_Mapping.py --input_file DDR4_unique_combinations_sorted.txt \
                     --whitelist_file Whitelist_withID.csv \
                     --output_file DDR4_Final_kmer_mapped_count_HD1_T100.csv \
                     --tolerance 1 \
                     --count_threshold 100

python 01_Mapping.py --input_file DDR4_unique_combinations_sorted.txt \
                     --whitelist_file Whitelist_withID.csv \
                     --output_file DDR4_Final_kmer_mapped_count_HD1_T50_kmer20.csv \
                     --tolerance 1 \
                     --count_threshold 50                             

python All_positions_mapping.py --input_file DDR5_unique_combinations_sorted.txt \
                                 --whitelist_file ${PROJECT_ROOT:-.}/Sub_info/Final_oligos_withID.csv \
                                 --output_file DDR5_unique_combinations_sorted_mapped.txt

python 01_Mapping.py --input_file DDR5_unique_combinations_sorted.txt \
                     --whitelist_file Whitelist_withID.csv \
                     --output_file DDR5_Final_kmer_mapped_count_HD1_T100.csv \
                     --tolerance 1 \
                     --count_threshold 100

python 01_Mapping.py --input_file DDR5_unique_combinations_sorted.txt \
                     --whitelist_file Whitelist_withID.csv \
                     --output_file DDR5_Final_kmer_mapped_count_HD1_T50_kmer20.csv \
                     --tolerance 1 \
                     --count_threshold 50     

# assemble final matrix
python 02_assemble_count_matrix.py --whitelist_file ${PROJECT_ROOT:-.}/Sub_info/Final_oligos_withID.csv \
                                   --output_file kmer_HD1_count_matrix.csv \
                                   --input_files DDR1_Final_kmer_mapped_count_HD1_T100.csv DDR2_Final_kmer_mapped_count_HD1_T100.csv DDR3_Final_kmer_mapped_count_HD1_T100.csv DDR4_Final_kmer_mapped_count_HD1_T100.csv DDR5_Final_kmer_mapped_count_HD1_T100.csv


python 02_assemble_count_matrix.py --whitelist_file ${PROJECT_ROOT:-.}/Sub_info/Final_oligos_withID.csv \
                                   --output_file kmer20_HD1_count_matrix.csv \
                                   --input_files DDR1_Final_kmer_mapped_count_HD1_T50_kmer20.csv DDR2_Final_kmer_mapped_count_HD1_T50_kmer20.csv DDR3_Final_kmer_mapped_count_HD1_T50_kmer20.csv DDR4_Final_kmer_mapped_count_HD1_T50_kmer20.csv DDR5_Final_kmer_mapped_count_HD1_T50_kmer20.csv

# test signficance using MAGack. NOTE, the output file kmer20_HD1_count_matrix.csv should be formatted as the following based on Magack count table format. 
mageck test -k kmer20_HD1_count_matrix_for_mageck.txt \
    -t DDR2,DDR4 \
    -c DDR1,DDR3 \
    --norm-method total \
    -n DDR_default 

mageck test -k kmer20_HD1_count_matrix_for_mageck.txt \
    -t DDR2,DDR4 \
    -c DDR1,DDR3 \
    --gene-test-fdr-threshold 0.25 \
    --norm-method total \
    -n DDR_fdr \
    --adjust-method fdr \
   
