# in bash load packages
module load python/3.10.x-anaconda 

# activate the conda env. The latest mageck has been installed under ISS env
conda activate ISS 

cd /project/pathology/SiZhang_lab/shared/Active_Projects/UTSW25_CC_DDR/RAW/01.RawData/DDR1


# grep target U6 handle sequences on beginning of R1. The pattern is GTGGAAAGGACGAAACACCG + Position 1 (20nt) + GTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAG 

(ISS) [s208205@Nucleus005 DDR1]$ zcat DDR1_CKDL240042575-1A_22TFMKLT3_L7_1.fq.gz | awk '(NR%4==2) && /GTGGAAAGGACGAAACACCG/' | head
ANGTGGAAAGGACGAAACACCGGTGCTGGGTGCTGTTGCCAGGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCAAGTGGCACCGAGTCGGTGCTTCAAGTAAACCCCTACCAACTGGTCGGGGTTTGAAACAGCG
GNAGGTGGAAAGGACGAAACACCGGGGCCTGGGACACTGATGAGGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGT
TNAAGGTGGAAAGGACGAAACACCGTCGGTGCGGCCCATCCCGGAGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATG
TNAAGGTGGAAAGGACGAAACACCGGGTCAAACTAGTCAGGGAGAGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATG
GNAGGTGGAAAGGACGAAACACCGGACCCTAACCAGGATCCTGCGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGT
TNAAGGTGGAAAGGACGAAACACCGGGCTTGCGCAGTGTCGACGCGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATG
TNAAGGTGGAAAGGACGAAACACCGACTTTCCCGGGGACCCCTGCGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATG
ANGTGGAAAGGACGAAACACCGGACCCTAACCAGGATCCTGCGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGTCT
ANGTGGAAAGGACGAAACACCGCATGCGCATCCAGTATCACGGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGTCT
GNAGGTGGAAAGGACGAAACACCGGGCGCTTGCCCGCCACCTGGGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGT

# grep R2 with handle at beginning of the reads TGACCGCTGAAGTACAAGTGGTAGAGTAG. The pattern is: TGACCGCTGAAGTACAAGTGGTAGAGTAG + BC(14nt) + A(7nt) + Position 2 RC (23nt) + GTTTCAAACCCC
(ISS) [s208205@Nucleus005 DDR1]$ zcat DDR1_CKDL240042575-1A_22TFMKLT3_L7_2.fq.gz | awk '(NR%4==2) && /TGACCGCTGAAGTACAAGTGGTAGAGTAG/' | head
TGACCGCTGAAGTACAAGTGGTAGAGTAGATAGACGTCTTGAGAAAAAAACAGGCCTTCTTACTTTATTCGCTGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGCACGTGTATTCACGAAAAAAACCTGGCTACTAAATATTTTATGTGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGAATAGCACAGGTGCAAAAAAATCTGGCAGTCTCATTCAGAATGGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGGCACTGTATACTTGAAAAAAATGCAGCAGCAATCTTGACTTCTGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGGTTCTTCTGGAGGAAAAAAAAAGTCTGTCACAAAGTCTATTCTGAGTTTCAAACCCCGACCAGTTGGTAGGGGTTTCCTTGAAGCACCGACTCGGTGTCACTTTGCCCCTCCGACACGGGT
TGACCGCTGAAGTACAAGTGGTAGAGTAGCTCTCGTGAAGTGAAAAAAAAGGCTGTGCTAAATAATGTCATTTGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGTAGGTAGCTATTGCAAAAAAATCTCGGGAAGCAGCTGTGGAAGCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGTTCTTCGAAGCATCAAAAAAATGGGGGTGATATGAAAGAGTGGTGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGCATAGTGACCATCAAAAAAAACAGGGCAAGCACTTCTTTCTTTAGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGCACGATATACGCGTAAAAAAAGTGCCTTGGACATTTTAAGTTGTGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG

# QC
fastp \
  -i DDR1_CKDL240042575-1A_22TFMKLT3_L7_1.fq.gz \
  -I DDR1_CKDL240042575-1A_22TFMKLT3_L7_2.fq.gz \
  -o DDR1_CKDL240042575-1A_22TFMKLT3_L7_out1.fq.gz \
  -O DDR1_CKDL240042575-1A_22TFMKLT3_L7_out2.fq.gz \
  --html DDR1_CKDL240042575-1A_22TFMKLT3_L7_fastp.html \
  --json DDR1_CKDL240042575-1A_22TFMKLT3_L7_fastp.json

# extraction and freq calculations
python UTSW25_DDR_BC_extraction.py -r1 DDR1_CKDL240042575-1A_22TFMKLT3_L7_1.fq.gz -r2 DDR1_CKDL240042575-1A_22TFMKLT3_L7_2.fq.gz -o DDR1_extraction_output.txt -l DDR1_extraction_output.log -p 100000
python calculate_frequencies.py -i DDR1_extraction_output.txt -o DDR1_unique_combinations_sorted.txt -v

# DDR2
cd /project/pathology/SiZhang_lab/shared/Active_Projects/UTSW25_CC_DDR/RAW/01.RawData/DDR2

(ISS) [s208205@Nucleus005 DDR2]$ zcat DDR2_CKDL240042575-1A_22TFMKLT3_L7_1.fq.gz | awk '(NR%4==2) && /GTGGAAAGGACGAAACACCG/' | head
ANGGTGGAAAGGACGAAACACCGCTCATCCAAGGCAGCCTGCGGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGTC
TNAAGGTGGAAAGGACGAAACACCGACACTGAGAAATACCCGCAGGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATG
TNAAGGTGGAAAGGACGAAACACCGCCAGTCGCGCCTCTCCAGAGGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATG
GNAGGTGGAAAGGACGAAACACCGGCAGCCAGGCTCGCGATGGGGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGT
GNAGGTGGAAAGGACGAAACACCGCGCCAAGCAGCCGCAGAGCAGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGT
GNAGGTGGAAAGGACGAAACACCGTCGGTGCGGCCCATCCCGGAGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGT
GNAGGTGGAAAGGACGAAACACCGTCTTAACCGCCCGTCTTGGTGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGT
GNAGGTGGAAAGGACGAAACACCGTCAGGATTGGCTCCTGCGTAGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGGATCACCCATG
TNAAGGTGGAAAGGACGAAACACCGGAGGAGCGCCCCAGTGGCCAGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATG
ANGTGGAAAGGACGAAACACCGCAGGACGCAACCCTATGAGTGTTTTAGAGCTAGGCCAACATGAGGATCACCCATGTCTGCAGGGCCTAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGGCCAACATGAGGATCACCCATGTCT

(ISS) [s208205@Nucleus005 DDR2]$ zcat DDR2_CKDL240042575-1A_22TFMKLT3_L7_2.fq.gz | awk '(NR%4==2) && /TGACCGCTGAAGTACAAGTGGTAGAGTAG/' | head
TGACCGCTGAAGTACAAGTGGTAGAGTAGTGGTGAACTGACGTAAAAAAATGCAGCAGCAATCTTGACTTCTGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGACACTCGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGGTATCGATACATCCAAAAAAACTTGGATGCATTTTTCTCTTTGTGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGTTGAGATCACAGTGAAAAAAAGCTGAGGCAGCTAAATTAGTTCCGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGCCTCCAATAATGGTAAAAAAATCCTGGCTACTAAATATTTTATGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGAGGTAACCTAGGTGAAAAAAACGTGCTCTCCTCTCTTTTGGTGGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGTGTTCGCAGGACTGAAAAAAAATTGGATGCATTTTTCTCTTTGTGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGTACTATCAGCCGCGAAAAAAATGCAGCAGCAATCTTGACTTCTGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG
TGACCGCTGAAGTACAAGTGGTAGAGTAGTTCGCACCACTTGTAAAAAAAAGGCTGTGCTAAATAATGTCATTTGTTTCAAACCCTGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGT
TGACCGCTGAAGTACAAGTGGTAGAGTAGCTGGAGCTCTCTAAAAAAAAAAACCTGTCCAAAGACGACTTGATAGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAGCACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGT
TGACCGCTGAAGTACAAGTGGTAGAGTAGCGTCCATCAACGAAAAAAAAACCTGGCTGCTACTGTTCCATGGGGTTTCAAACCCCGACCAGTTGGTAGGGGTTTACTTGAAACACCGACTCGGTGCCACTTGGCCCTGCAGACATGGGTG

# QC
fastp \
  -i DDR2_CKDL240042575-1A_22TFMKLT3_L7_1.fq.gz \
  -I DDR2_CKDL240042575-1A_22TFMKLT3_L7_2.fq.gz \
  -o DDR2_CKDL240042575-1A_22TFMKLT3_L7_out1.fq.gz \
  -O DDR2_CKDL240042575-1A_22TFMKLT3_L7_out2.fq.gz \
  --html DDR2_CKDL240042575-1A_22TFMKLT3_L7_fastp.html \
  --json DDR2_CKDL240042575-1A_22TFMKLT3_L7_fastp.json

# extract position sequences and calcualte frequencies for all samples
python UTSW25_DDR_BC_extraction.py -r1 DDR2_CKDL240042575-1A_22TFMKLT3_L7_1.fq.gz -r2 DDR2_CKDL240042575-1A_22TFMKLT3_L7_2.fq.gz -o DDR2_extraction_output.txt -l DDR2_extraction_output.log -p 100000
python calculate_frequencies.py -i DDR2_extraction_output.txt -o DDR2_unique_combinations_sorted.txt -v

python UTSW25_DDR_BC_extraction.py -r1 DDR3_CKDL240042575-1A_22TFMKLT3_L7_1.fq.gz -r2 DDR3_CKDL240042575-1A_22TFMKLT3_L7_2.fq.gz -o DDR3_extraction_output.txt -l DDR2_extraction_output.log -p 100000
python calculate_frequencies.py -i DDR3_extraction_output.txt -o DDR3_unique_combinations_sorted.txt -v

python UTSW25_DDR_BC_extraction.py -r1 DDR4_CKDL240042575-1A_22TFMKLT3_L7_1.fq.gz -r2 DDR4_CKDL240042575-1A_22TFMKLT3_L7_2.fq.gz -o DDR4_extraction_output.txt -l DDR2_extraction_output.log -p 100000
python calculate_frequencies.py -i DDR4_extraction_output.txt -o DDR4_unique_combinations_sorted.txt -v

python UTSW25_DDR_BC_extraction.py -r1 DDR5_CKDL240042575-1A_22TFMKLT3_L7_1.fq.gz -r2 DDR5_CKDL240042575-1A_22TFMKLT3_L7_2.fq.gz -o DDR5_extraction_output.txt -l DDR2_extraction_output.log -p 100000
python calculate_frequencies.py -i DDR5_extraction_output.txt -o DDR5_unique_combinations_sorted.txt -v

# map the frequencies to the whitelist
python All_positions_mapping.py --input_file DDR1_unique_combinations_sorted.txt \
                                 --whitelist_file /project/pathology/SiZhang_lab/shared/Active_Projects/UTSW25_CC_DDR/Sub_info/Final_oligos_withID.csv \
                                 --output_file DDR1_unique_combinations_sorted_mapped.txt

python All_positions_mapping_HD1.py --input_file DDR1_unique_combinations_sorted.txt \
                                 --whitelist_file /project/pathology/SiZhang_lab/shared/Active_Projects/UTSW25_CC_DDR/Sub_info/Final_oligos_withID.csv \
                                 --output_file DDR1_unique_combinations_sorted_mapped_HD1.txt

python All_positions_mapping.py --input_file DDR2_unique_combinations_sorted.txt \
                                 --whitelist_file /project/pathology/SiZhang_lab/shared/Active_Projects/UTSW25_CC_DDR/Sub_info/Final_oligos_withID.csv \
                                 --output_file DDR2_unique_combinations_sorted_mapped.txt

python All_positions_mapping.py --input_file DDR3_unique_combinations_sorted.txt \
                                 --whitelist_file /project/pathology/SiZhang_lab/shared/Active_Projects/UTSW25_CC_DDR/Sub_info/Final_oligos_withID.csv \
                                 --output_file DDR3_unique_combinations_sorted_mapped.txt

python All_positions_mapping.py --input_file DDR4_unique_combinations_sorted.txt \
                                 --whitelist_file /project/pathology/SiZhang_lab/shared/Active_Projects/UTSW25_CC_DDR/Sub_info/Final_oligos_withID.csv \
                                 --output_file DDR4_unique_combinations_sorted_mapped.txt

python All_positions_mapping.py --input_file DDR5_unique_combinations_sorted.txt \
                                 --whitelist_file /project/pathology/SiZhang_lab/shared/Active_Projects/UTSW25_CC_DDR/Sub_info/Final_oligos_withID.csv \
                                 --output_file DDR5_unique_combinations_sorted_mapped.txt

# assemble final matrix
python assemble_count_matrix.py --whitelist_file /project/pathology/SiZhang_lab/shared/Active_Projects/UTSW25_CC_DDR/Sub_info/Final_oligos_withID.csv \
                                --output_file count_matrix.csv \
                                --input_files DDR1_unique_combinations_sorted_mapped.txt DDR2_unique_combinations_sorted_mapped.txt DDR3_unique_combinations_sorted_mapped.txt DDR4_unique_combinations_sorted_mapped.txt DDR5_unique_combinations_sorted_mapped.txt

